### ISSUE TITLE
Connection Timed Out Error 

### ISSUE THREAD

**Issue by janathaworth** [mohdumar644/TinyYOLO-BNN#3]
HI! 

I am just trying to run the TinyYOLO_Loop.ipynb but I get the error included below. Could you help me understand what I am doing wrong? Thank you!

Thing I tried (both give same error): 
I tried cloning this repo and running the TinyYOLO_Loop.ipynb file from the BNN-PYNQ directory after renaming the bit and tcl file and placing them under a folder called pynqZ1-Z2 in the bitstreams directory. 

I also tried pip installing the Xilinx/BNN-PYNQ repository and replacing the bitstream files with the ones included in this repository and recompiling the libraries with make-sw.sh.

ERROR: 
`TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-ce000b8716f6>", line 53, in <module>
    hw_classifier = bnn.CnvClassifier(bnn.NETWORK_CNVW1A1,'tinyyolo',bnn.RUNTIME_HW)
  File "/home/xilinx/jupyter_notebooks/TinyYOLO-BNN/BNN-PYNQ/bnn/bnn.py", line 192, in _init_
    self.bnn = PynqBNN(runtime, network)
  File "/home/xilinx/jupyter_notebooks/TinyYOLO-BNN/BNN-PYNQ/bnn/bnn.py", line 96, in _init_
    Overlay(self.bitstream_path).download()
  File "/usr/local/lib/python3.6/dist-packages/pynq/overlay.py", line 315, in _init_
    self.download()
  File "/usr/local/lib/python3.6/dist-packages/pynq/overlay.py", line 379, in download
    super().download()
  File "/usr/local/lib/python3.6/dist-packages/pynq/pl.py", line 1945, in download
    fd.write(self.binfile_name)
TimeoutError: [Errno 110] Connection timed out`

**Comment by janathaworth** [comment]
This is a problem for my other jupyter notebooks, too. Sorry, should have tested that first.

**Comment by janathaworth** [comment]
I've actually continued to see this error (once I run the notebook any other notebook that tries to load an overlay also gets the same error). I am not sure if it is because the bitstreams are incompatible with my board. I tried to create my own bitstreams using make-hw.sh but it does not progress past Do MemInit module

**Comment by mohdumar644** [comment]
Yeah they are incompatible with 7z020. I should have made that more explicit.
